### ISSUE TITLE
[BUG] is_datetime_or_timedelta removed in Pandas 2.1.0

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/opensearch-py-ml#263]
**What is the bug?**
We import `is_datetime_or_timedelta` in `field_mappings.py` but that has been removed from Pandas version 2.1.0. 

**How can one reproduce the bug?**
1. pip install pandas==2.1.0
2. from opensearch_py_ml.ml_commons import MLCommonClient
3. run the file

**What is the expected behavior?**
Should not give import error. 

**What is your host/environment?**
N/A

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by bsowell** [comment]
I was bit by this one recently. @dtaivpp @dhrubo-os I'm not familiar with the CCI label -- is this one somebody is working on, or would you take a PR?

**Comment by dhrubo-os** [comment]
> I was bit by this one recently. @dtaivpp @dhrubo-os I'm not familiar with the CCI label -- is this one somebody is working on, or would you take a PR?

 Currently no body is working on this issue. I marked this as `CCI` so that our next college contributors can work on this issue. PRs are welcome.

**Comment by bsowell** [comment]
Got it. Thanks! Let me look into it and see if I can contribute something.

**Comment by rawwar** [comment]
I see that a quick fix for this is to limit the version of pandas to < 2.0 .

**Comment by dhrubo-os** [comment]
>I see that a quick fix for this is to limit the version of pandas to < 2.0 .

Yeah, we can just do: `pandas>=1.5.2,<2.0` for a quick fix.

@bsowell are you working on this issue? Just checking.

**Comment by bsowell** [comment]
I'm sorry. I had trouble getting tests to run locally and then got distracted so I haven't done much. The implementation of `is_datetime_or_timedelta_dtype` is straightforward, so if there is value in upgrading pandas, it would be easy enough to just include the logic in field_mappings.py, but agree that the dependency change would be faster.

**Comment by Yerzhaisang** [comment]
I think we should close this issue. ```is_datetime_or_timedelta``` is not used anymore

**Comment by dhrubo-os** [comment]
Closing this issue in favor of https://github.com/opensearch-project/opensearch-py-ml/pull/316

**Comment by Jon-AtAWS** [comment]
I'm hitting this error now with opensearch-py-ml 1.1.0 and pandas 2.2.3. @Yerzhaisang you say it's not used any more, but I am facing this error

```
Traceback (most recent call last):
  File "/Users/handler/opensearch-ml-quickstart/main.py", line 11, in <module>
    from client import (
  File "/Users/handler/opensearch-ml-quickstart/client/__init__.py", line 4, in <module>
    from .os_ml_client_wrapper import OsMlClientWrapper
  File "/Users/handler/opensearch-ml-quickstart/client/os_ml_client_wrapper.py", line 6, in <module>
    from opensearch_py_ml.ml_commons import MLCommonClient
  File "/Users/handler/opensearch-ml-quickstart/.venv/lib/python3.12/site-packages/opensearch_py_ml/__init__.py", line 28, in <module>
    from .dataframe import DataFrame
  File "/Users/handler/opensearch-ml-quickstart/.venv/lib/python3.12/site-packages/opensearch_py_ml/dataframe.py", line 47, in <module>
    from opensearch_py_ml.groupby import DataFrameGroupBy
  File "/Users/handler/opensearch-ml-quickstart/.venv/lib/python3.12/site-packages/opensearch_py_ml/groupby.py", line 28, in <module>
    from opensearch_py_ml.query_compiler import QueryCompiler
  File "/Users/handler/opensearch-ml-quickstart/.venv/lib/python3.12/site-packages/opensearch_py_ml/query_compiler.py", line 44, in <module>
    from opensearch_py_ml.field_mappings import FieldMappings
  File "/Users/handler/opensearch-ml-quickstart/.venv/lib/python3.12/site-packages/opensearch_py_ml/field_mappings.py", line 44, in <module>
    from pandas.core.dtypes.common import (
ImportError: cannot import name 'is_datetime_or_timedelta_dtype' from 'pandas.core.dtypes.common' (/Users/handler/opensearch-ml-quickstart/.venv/lib/python3.12/site-packages/pandas/core/dtypes/common.py)
```

**Comment by Yerzhaisang** [comment]
@Jon-AtAWS Hi sir! Hope you are doing well.
opensearch-py-ml 1.1.0 released Jul 27, 2023, but the [PR](https://github.com/opensearch-project/opensearch-py-ml/pull/316) was merged on Nov 13, 2023. I believe you won't have this problem on the next release.

Good luck!

**Comment by Jon-AtAWS** [comment]
@Yerzhaisang this now works for me, but I was only able to get it working with Python 3.10, and Pandas 2.0.3. Those are the latest versions that worked for me. 

Since the latest python is 3.12, and the latest pandas is 2.2.3, you need to roll back Python to get it working.

I believe that https://github.com/opensearch-project/opensearch-py-ml/pull/316 is supposed to fix this. It becomes more urgent as both Python and Pandas have moved far forward.

**Comment by Yerzhaisang** [comment]
@Jon-AtAWS You are absolutely correct. `is_datetime_or_timedelta_dtype ` is still not deprecated on Pandas 2.0.3.
#316 already fixed that, and this deprecated name will no longer be imported in the next release.

**Comment by dhrubo-os** [comment]
@Jon-AtAWS we are planning to release a version soon. But in the meantime, you can installed the current development in your end through this: `pip install git+https://github.com/opensearch-project/opensearch-py-ml.git`. Then this should work with updated panda versions.

**Comment by techkuz** [comment]
> [@Jon-AtAWS](https://github.com/Jon-AtAWS) we are planning to release a version soon. But in the meantime, you can install the current development in your end through this: `pip install git+https://github.com/opensearch-project/opensearch-py-ml.git`. Then this should work with updated panda versions.

doesn't help

**Comment by Yerzhaisang** [comment]
> > [@Jon-AtAWS](https://github.com/Jon-AtAWS) we are planning to release a version soon. But in the meantime, you can install the current development in your end through this: `pip install git+https://github.com/opensearch-project/opensearch-py-ml.git`. Then this should work with updated panda versions.
> 
> doesn't help

before using this command, the module should be fully removed. Please, run the following:
`pip uninstall opensearch_py_ml`
Then you can install in your end through this: `pip install git+https://github.com/opensearch-project/opensearch-py-ml.git`
